### ISSUE TITLE
allocate_tod=False not working

### ISSUE THREAD

**Issue by paganol** [litebird/litebird_sim#111]
The constructor of Observations calls 
https://github.com/litebird/litebird_sim/blob/35b67bab655d5f6cf7dc1c62431580774fe07690/litebird_sim/observations.py#L126
which assumes that the tod attribute exists. This is not true when allocate_tod is set to false

**Comment by ziotom78** [comment]
Hi @paganol, thanks for the report. It's not obvious to me why `Observation.setattr_det_global` should mess with the TOD, but it's probably due to consistency checks (the field `self.tod` appears twice in the body of the method, and in both cases it is within an `assert`), so it is probably ok to avoid them if `self.tod` is `None`.

@dpole , what do you think?
