### ISSUE TITLE
Implement a way to split observations among different MPI processes

### ISSUE THREAD

**Issue by ziotom78** [litebird/litebird_sim#14]
When a simulation spans very long time scales or uses many detectors, parallelization on via MPI is probably the best way to go. The `Simulation` object should provide some tools to ease the task of distributing computing tasks among MPI processes. This will require the merging of #6 .

**Comment by dpole** [comment]
I think we should consider to delegate this task distribution and scheduling functionality to an external library (MPI just provides the communication mechanism). What about using Dask?

Maybe I should put it on a separate issue, but one possibility is also to use xarrays for timestream data (which are basically numpy arrays capable of storing also units and other metadata). In this case it would also allow some parallelization on distributed arrays out of the box (using Dask, that's why I mention it here).

**Comment by dpole** [comment]
Some resources
https://docs.dask.org/en/latest/why.html
http://xarray.pydata.org/en/stable/dask.html

Note that Dask also provides natively some live inspection of the running code (basic information about cores activity, code profiling, memory and CPU usage...). Of course this has some overhead in terms of computational time, dependencies, and boilerplate code (which however would be much shorter than writing something on our own)

**Comment by mreineck** [comment]
I'm worried that the amount of external dependencies might get a bit out of hand. Personally I wouldn't be happy if I had to download hundreds of MB just to run a LiteBIRD simulation, no matter how small. But I admit that's a matter of personal taste :)

**Comment by dpole** [comment]
I fully agree that we should minimize dependencies. I wouldn't use the software size as a criterion. I am more concerned about complicating the install process and reducing the portability of the code.
I also love writing my own code instead of adding a dependency, but in most cases it ends up taking me quite a bit of time for a worse final result.
We should judge on a case by case basis, and discuss clearly why a dependency should be added or avoided. I'm happy to be more specific about dask

**Comment by dpole** [comment]
This was done. As of #42 we can both distribute a list of observations and distribute individual observations over a communicator
