### ISSUE TITLE
Small installation problems

### ISSUE THREAD

**Issue by mreineck** [litebird/litebird_sim#17]
I followed the installation instructions from README.md and encountered a small problem:
While running `bin/run_tests.sh` the script complained about missing `black` and `flake8`, although they had been installed during the `poetry install` step. Installing these packages system-wide did help, but that's probably not the preferred solution.

Another point: I know it's fashionable these days, but I really feel bad about encouraging people to execute commands like
    ```
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    ```
(with or without `sudo`). It's extremely bad practice and dangerous. Personally I will never run such a command, unless I'm on a throw-away virtual machine. Is there a reason to prefer this over, say, `pip3 install --user poetry`?

**Comment by ziotom78** [comment]
Done, it was a trivial error. (The Windows `run_test.bat` script was already ok, don't know why the bash script was wrong.)

Regarding the second point, I feel it's as dangerous as decompressing a `.tar.gz` file downloaded somewhere and running the `configure` in it, which is the way we have always installed libraries like CFITSIO and Healpix. (Same with Python libraries that require `python setup.py install`.)

The page https://python-poetry.org/docs/#installation says that the Poetry developers suggest this method because the user can be 100% sure that `poetry` will work with the `python` executable used in that call. The alternate method provided in the page (using `pip`) requires that `pip3` and `python` match; and I have experienced this not be the case in sooo many situations… 😟 (E.g., one being the version provided by the system, and the other being the package provided by Anaconda.) The best option would be to install `poetry` using the package manager provided by the SO, but I have not checked how widely available is Poetry on common package-management systems. (Moreover, package managers usually require to use `sudo`, which might not be possible for users of HPC systems.)

Perhaps I could add a line saying that one can use `pip` to install Poetry, with the warning to check that the `pip` executable matches the `python` executable one's going to use. What do you think?

**Comment by mreineck** [comment]
> Done, it was a trivial error. (The Windows run_test.bat script was already ok, don't know why the bash script was wrong.)

Great, thanks a lot!

> Regarding the second point, I feel it's as dangerous as decompressing a .tar.gz file downloaded somewhere and running the configure in it.

You are right. There are ways to mitigate the risk with a tar file (e.g. re-running `autoconf` or at least verifying checksums), but I agree that not many people are sufficiently paranoid.
Piping downloaded code directly into the interpreter just feels too much like "taking sweets from strangers" to me; that's a childhood lesson I'll never get completely rid of.
