### ISSUE TITLE
CMB monopole and dipole

### ISSUE THREAD

**Issue by NicolettaK** [litebird/litebird_sim#41]
Hi, shall we agree on how to simulate the CMB monopole and dipole? I can then add them in the map-based-sim module.

**Comment by ziotom78** [comment]
I think we should aim to simulate the dipolar and quadrupolar components; for the orbital component, I suggest we just use the Earth's barycenter instead of the L2 point, as it's already included in AstroPy's ephemerides tables.

**Comment by mreineck** [comment]
I suggest to avoid simulating the monopole. It only causes numerical trouble, because it is a huge constant added to very small fluctuations, and that hurts accuracy a lot. I guess that's also the reason why most CMB experiments are custom-tailored to _not_ measure the monopole :)

For the dipole and quadrupole, would it be OK to expect as input a time-varying satellite location vector? Then the required quantities can be easily evaluated using the satellite speed from this input.
As long as we don't have anything better, we can put the Earth's location into that input array. Once we know more about the trajectory, we can just plug that in and the results will instantly be better without any further code change,

**Comment by paganol** [comment]
I agree with @mreineck. It would be also nice to have several options for generating all the terms, or only the dipole, or for including or not the frequency dependence of the high order terms, and so on. Something similar to what LevelS does.

**Comment by tomma90** [comment]
I agree with @mreineck and @paganol for dipole and quadrupole. 

If it's not too much work I think including the possibility to simulate the monopole can be very useful for detector-related studies, because the operation point of the detector depends on the total optical loading which is dominated by the monopole. HWP imperfections studies also may need the full optical loading.

**Comment by ziotom78** [comment]
I agree that the monopole is far less relevant than the dipole, but I still think we should provide the ability to inject it in the simulations. This can be relevant when one wants to compute the overall optical load on a bolometer, or to properly model the background when simulating the observation of point sources.

@mreineck , yout idea about the array of vector positions seems the best.

**Comment by mreineck** [comment]
I wasn't aware of the use cases for the monopole ... in that case I agree there should be an option to put it in.

Since @paganol mentioned LevelS: please feel free to take all the necessary formulas from there if that saves you time! This should be a part of LevelS which can be used with almost no functional change.

**Comment by NicolettaK** [comment]
Ok thanks! I think I would need the help of someone who is more familiar than me on dipole to implement the code.
Also, I don't think I have access anymore to LevelS, is it available somewhere?

**Comment by paganol** [comment]
This is the relevant pice of code. I can help here
[dipole.cc.zip](https://github.com/litebird/litebird_sim/files/4850359/dipole.cc.zip)

**Comment by mreineck** [comment]
The public release of LevelS is archived here: https://sourceforge.net/projects/planck-ls/

**Comment by NicolettaK** [comment]
Thanks!

**Comment by paganol** [comment]
PR #122 addressed this issue. We can close it
