### ISSUE TITLE
Make ducc0 optional?

### ISSUE THREAD

**Issue by ickc** [litebird/litebird_sim#91]
c.f. #90, ducc0 uses too much memory for readthedocs, and is only called once.
Should we make it optional and put it somewhere in `[tool.poetry.extras]` in `pyproject.toml`?

**Comment by mreineck** [comment]
I don't think you can make the package "truly" optional, as it is mandatory for pointing calculations and will become mandatory for more things in the future,
But we can certainly find a workaround for this; one way is to upload a binary wheel that just has generic optimizations for x86_64, so it doesn't have to be built on the fly. I'm not perfectly happy with this, since it means that most users will live with suboptimal performance, because they are too lazy to compile the package themselves.
Any other ideas?

**Comment by ickc** [comment]
Currently in #90, the way to deal with this is to have a separate docs/requirements.txt that is manually matched from pyproject.toml to install just enough packages to build the documentation. Manually syncing between these 2 files is not a good long term solution.

So one way is to just put ducc0 in an "extras", say, "full". But it means that every time ducc0 is imported then it has to be expected some installation might not have it (such as putting the import inside function calls, or set it to None and handle it 
later.) But this is not a very good user experience either.

I think as you said providing a prebuilt binary is the way to go. PyPI should be aimed for good user experience, not necessarily optimization. For slightly more complicated setup, conda is preferred comparing to pip (such as when a project has a lot of non-pure-python dep.) And for optimal setup such as running on HPC (especially those with AVX512) then a custom optimized environment is needed (so no nice package manager helping here.) *But*, May be a word of warning should be mentioned to point out this and provide a convenient command for people to install from sdist instead of wheel.

**Comment by ziotom78** [comment]
Thanks for having created this issue, @ickc . So far, the philosophy we've followed in implementing the framework was to leave all the C++ code used by the framework in `ducc0` and keep all the Python code in `litebird_sim`.

Apart from pointing generation, we plan to use `ducc0` for map-making (through the interface `pyhealpix`) and for beam-convolution, and the Sphinx documentation needs a quite complete system to run the doctests (which are currently less than planned).

I believe that the best solution would to specify a binary wheel in `docs/requirement.txt` and ask to use the source package for the framework itself. However, I do not know if this can be accomplished and how!

**Comment by ziotom78** [comment]
After some investigation, I found these issues in Poetry:

https://github.com/python-poetry/poetry/issues/1316

It seems that a workaround would be to instruct people to install `litebird_sim` in the following way:

1.  Download the `.tar.gz` file;
2.  Install it using the command `pip install --no-binary ducc0 litebird-sim-X.Y.Z.tar.gz`.

(The `.tar.gz` file created by Poetry does not depend on Poetry itself, and thus the above issue is not relevant there.)

**Comment by dpole** [comment]
If I understand correctly, the whole problem comes from the fact that we are using readthedocs for testing (doctests aside, building the doc does not require a working library, right?). In this case, we should probably leave the testing part to GHA only (which have to install everything anyway).
This would also speed up doc building enormously.

**Comment by ziotom78** [comment]
> doctests aside, building the doc does not require a working library, right?

Well, unfortunately this is not true: Sphinx runs the code and places the output (messages and plots) in the documentation itself. In this way one can be sure that the documentation is always synchronized with the code.

**Comment by ickc** [comment]
> I believe that the best solution would to specify a binary wheel in `docs/requirement.txt` and ask to use the source package for the framework itself. However, I do not know if this can be accomplished and how!

The problem with the current fix in #90 in the long run is that one has to manually sync between pyproject.toml and docs/requirements.txt which duplicated some of the dep spec. I think the either of the 3 suggestions I made above would solve the issues but it depends which directions you'd want to go about it.

IMO the most straight forward way would be just provide wheel for ducc0, because using a package manager (especially as rudimentary as pip) is not about optimization. And I don't know if packaging to conda-forge is planned, if so, AFAIK there's no way to build from source only in conda-forge, it has to be prebuilt binaries so we're back to the un-optimized situation if we want to use a better package manager from pip to conda.

**Comment by ziotom78** [comment]
I like the idea of providing a binary wheel for `ducc0`, provided that we clearly write in the installation instructions that you have to install the code using the command

```
pip install --no-binary ducc0 litebird-sim-X.Y.Z.tar.gz
```

Sure, whenever one uses poetry, the binary wheel will be installed, as long as bug [#1316](https://github.com/python-poetry/poetry/issues/1316) is not fixed. However, poetry is meant to be used by litebird_sim's developers only: every other user is expected to create their own virtual environments and use `pip` to install our framework. (I usually do the same when I write code that uses our framework and advise everybody to do so.)

However, there are a couple of potential issues with this approach:

1.  I have not tested the `pip install --no-binary` command yet, so I am not sure that it will do what we expect. May somebody test it?
2.  I understand Martin's wish to be sure that users use ducc0 under the best possible conditions; I know that Martin spent a lot of time fiddling with SIMD and AVX tricks to ensure the best possible throughput for ducc0. Providing a binary wheel on the PyPI site would disable these optimization for nearly all the case, because once ducc0 is available on PyPI, everybody but the most careful users is going to use it.
3. We must remember that ducc0 is going to be used not only by litebird_sim, so I would like to pick a solution that affects ducc0 the least.

A possible compromise would be to make the ducc0 binary wheels available somewhere (*not* on PyPI) and force ReadTheDocs to grab and install these binary copies. What do you think?

**Comment by ickc** [comment]
> as long as bug [#1316](https://github.com/python-poetry/poetry/issues/1316) is not fixed

One possible compromise is to use the setup.py generated by poetry and install from there. Furthermore, this same trick enables `pip install -e .` which AFAIK is not possible in poetry.

> and force ReadTheDocs to grab and install these binary copies

The problem is that in the long run it is not a good idea to maintain 2 different files specifying the same dep and requires manually syncing between them: pyproject.toml and docs/requirements.txt. So I think a better solution is just to not special casing readthedocs (e.g. putting ducc0 as optional dependencies or provide prebuilt binaries.)

**Comment by mreineck** [comment]
How about this completely different approach: I could update ducc's `setup.py` to check for, say, the environment variable `DUCC0_COMPILE_NOOPT` and simply disable all optimizations if it is defined. That makes compilation much less resource-hungry.

Would this help?

**Comment by ziotom78** [comment]
@mreineck , I like this approach a lot! It would simplify the deployment of ducc on *any* low-resource container.

**Comment by mreineck** [comment]
Great, that should be easy to do!
I just wasn't entirely sure whether you have control over environment variables at the point where the package is installed.

**Comment by ziotom78** [comment]
> I just wasn't entirely sure whether you have control over environment variables at the point where the package is installed.

Yes, I checked and it seems that there is the possibility to pass environment variables to Readthedocs' build environment:

https://docs.readthedocs.io/en/stable/guides/environment-variables.html

**Comment by mreineck** [comment]
How much memory do we have for the readthedocs compilation? I'm seeing a gcc memory usage of roughly 1.2GB even without optimization and debugging.

**Comment by dpole** [comment]
I think it is 3GB
https://docs.readthedocs.io/en/stable/builds.html

**Comment by mreineck** [comment]
How about https://github.com/litebird/ducc/tree/add_compilation_strategy?

**Comment by mreineck** [comment]
(I'll add documentation once we agree that this is the way to go.)

**Comment by ziotom78** [comment]
I like the versatility here:

```python
compilation_strategy = os.getenv('DUCC0_OPTIMIZATION', 'native')
if compilation_strategy not in ['none', 'portable', 'portable-debug', 'native', 'native-debug']:
    raise RuntimeError('unknown compilation strategy')
```

If I understand well, we should probably use `portable-debug` in Readthedocs, right?

**Comment by mreineck** [comment]
> If I understand well, we should probably use portable-debug in Readthedocs, right?

If you want minimum resoutce consumption, you should use `none`.

**Comment by mreineck** [comment]
Any more feedback, or should I merge this to `ducc` master?

**Comment by ziotom78** [comment]
For me the idea looks great, please go on!

**Comment by mreineck** [comment]
Great! I just did the merge.

How urgent is it to have a new release on PyPI with this? If it can wait for a few days, I'd like to merge some other things, update the ChangeLog etc.

**Comment by ziotom78** [comment]
Not very urgent, I dare say. We can live with Readthedocs builds that occasionally fail.

**Comment by mreineck** [comment]
Version 0.8 is now released on PyPI.
